/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'AMRDataMsg'
 * message type.
 */

public class AMRDataMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 52;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 90;

    /** Create a new AMRDataMsg of size 52. */
    public AMRDataMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new AMRDataMsg of the given data_length. */
    public AMRDataMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AMRDataMsg with the given data_length
     * and base offset.
     */
    public AMRDataMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AMRDataMsg using the given byte array
     * as backing store.
     */
    public AMRDataMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AMRDataMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public AMRDataMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AMRDataMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public AMRDataMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AMRDataMsg embedded in the given message
     * at the given base offset.
     */
    public AMRDataMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AMRDataMsg embedded in the given message
     * at the given base offset and length.
     */
    public AMRDataMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <AMRDataMsg> \n";
      try {
        s += "  [counter=0x"+Long.toHexString(get_counter())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [current=";
        for (int i = 0; i < 25; i++) {
          s += "0x"+Long.toHexString(getElement_current(i) & 0xffff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: counter
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'counter' is signed (false).
     */
    public static boolean isSigned_counter() {
        return false;
    }

    /**
     * Return whether the field 'counter' is an array (false).
     */
    public static boolean isArray_counter() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'counter'
     */
    public static int offset_counter() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'counter'
     */
    public static int offsetBits_counter() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'counter'
     */
    public int get_counter() {
        return (int)getUIntBEElement(offsetBits_counter(), 16);
    }

    /**
     * Set the value of the field 'counter'
     */
    public void set_counter(int value) {
        setUIntBEElement(offsetBits_counter(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'counter'
     */
    public static int size_counter() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'counter'
     */
    public static int sizeBits_counter() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: current
    //   Field type: int[], unsigned
    //   Offset (bits): 16
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'current' is signed (false).
     */
    public static boolean isSigned_current() {
        return false;
    }

    /**
     * Return whether the field 'current' is an array (true).
     */
    public static boolean isArray_current() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'current'
     */
    public static int offset_current(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 25) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'current'
     */
    public static int offsetBits_current(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 25) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'current' as a int[]
     */
    public int[] get_current() {
        int[] tmp = new int[25];
        for (int index0 = 0; index0 < numElements_current(0); index0++) {
            tmp[index0] = getElement_current(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'current' from the given int[]
     */
    public void set_current(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_current(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'current'
     */
    public int getElement_current(int index1) {
        return (int)getUIntBEElement(offsetBits_current(index1), 16);
    }

    /**
     * Set an element of the array 'current'
     */
    public void setElement_current(int index1, int value) {
        setUIntBEElement(offsetBits_current(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'current'
     */
    public static int totalSize_current() {
        return (400 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'current'
     */
    public static int totalSizeBits_current() {
        return 400;
    }

    /**
     * Return the size, in bytes, of each element of the array 'current'
     */
    public static int elementSize_current() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'current'
     */
    public static int elementSizeBits_current() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'current'
     */
    public static int numDimensions_current() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'current'
     */
    public static int numElements_current() {
        return 25;
    }

    /**
     * Return the number of elements in the array 'current'
     * for the given dimension.
     */
    public static int numElements_current(int dimension) {
      int array_dims[] = { 25,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

}
