/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'PCControlMsg'
 * message type.
 */

public class PCControlMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 12;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 137;

    /** Create a new PCControlMsg of size 12. */
    public PCControlMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new PCControlMsg of the given data_length. */
    public PCControlMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PCControlMsg with the given data_length
     * and base offset.
     */
    public PCControlMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PCControlMsg using the given byte array
     * as backing store.
     */
    public PCControlMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PCControlMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public PCControlMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PCControlMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public PCControlMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PCControlMsg embedded in the given message
     * at the given base offset.
     */
    public PCControlMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PCControlMsg embedded in the given message
     * at the given base offset and length.
     */
    public PCControlMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <PCControlMsg> \n";
      try {
        s += "  [param=";
        for (int i = 0; i < 6; i++) {
          s += "0x"+Long.toHexString(getElement_param(i) & 0xffff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: param
    //   Field type: int[], unsigned
    //   Offset (bits): 0
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'param' is signed (false).
     */
    public static boolean isSigned_param() {
        return false;
    }

    /**
     * Return whether the field 'param' is an array (true).
     */
    public static boolean isArray_param() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'param'
     */
    public static int offset_param(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 6) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'param'
     */
    public static int offsetBits_param(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 6) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'param' as a int[]
     */
    public int[] get_param() {
        int[] tmp = new int[6];
        for (int index0 = 0; index0 < numElements_param(0); index0++) {
            tmp[index0] = getElement_param(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'param' from the given int[]
     */
    public void set_param(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_param(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'param'
     */
    public int getElement_param(int index1) {
        return (int)getUIntBEElement(offsetBits_param(index1), 16);
    }

    /**
     * Set an element of the array 'param'
     */
    public void setElement_param(int index1, int value) {
        setUIntBEElement(offsetBits_param(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'param'
     */
    public static int totalSize_param() {
        return (96 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'param'
     */
    public static int totalSizeBits_param() {
        return 96;
    }

    /**
     * Return the size, in bytes, of each element of the array 'param'
     */
    public static int elementSize_param() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'param'
     */
    public static int elementSizeBits_param() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'param'
     */
    public static int numDimensions_param() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'param'
     */
    public static int numElements_param() {
        return 6;
    }

    /**
     * Return the number of elements in the array 'param'
     * for the given dimension.
     */
    public static int numElements_param(int dimension) {
      int array_dims[] = { 6,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

}
